from __future__ import annotations

import argparse
from contextlib import nullcontext
import logging
import math
import os
import sys
from typing import List, Sequence, Tuple


def parse_args(args: Sequence[str]):
    parser = argparse.ArgumentParser(
        description="Generate offline teacher CLIP features for image-text pairs."
    )
    parser.add_argument(
        "--output-cache",
        type=str,
        required=True,
        help="Path to the output cache file saved with torch.save.",
    )
    parser.add_argument(
        "--teacher-model",
        type=str,
        default="RN50",
        help="Teacher CLIP model architecture name.",
    )
    parser.add_argument(
        "--teacher-pretrained",
        type=str,
        default="",
        help="Teacher pretrained tag or checkpoint path.",
    )
    parser.add_argument(
        "--batch-size",
        type=int,
        default=64,
        help="Batch size used for cache generation.",
    )
    parser.add_argument(
        "--workers",
        type=int,
        default=1,
        help="Number of dataloader workers.",
    )
    parser.add_argument(
        "--device",
        type=str,
        default=None,
        help="Device to run on. Defaults to cuda if available else cpu.",
    )
    parser.add_argument(
        "--precision",
        choices=["amp", "amp_bf16", "amp_bfloat16", "bf16", "fp16", "fp32"],
        default="fp32",
        help="Model precision for inference.",
    )
    parser.add_argument(
        "--train-data",
        type=str,
        default=None,
        help="Training data path. If set, cache is generated from this split.",
    )
    parser.add_argument(
        "--val-data",
        type=str,
        default=None,
        help="Validation data path. Used when --train-data is not set.",
    )
    parser.add_argument(
        "--train-num-samples",
        type=int,
        default=None,
        help="Number of samples in the training dataset when not discoverable.",
    )
    parser.add_argument(
        "--val-num-samples",
        type=int,
        default=None,
        help="Number of samples in the validation dataset when not discoverable.",
    )
    parser.add_argument(
        "--data-root",
        type=str,
        default=None,
        help="Dataset root for training data.",
    )
    parser.add_argument(
        "--val-data-root",
        type=str,
        default=None,
        help="Dataset root for validation data.",
    )
    parser.add_argument(
        "--dataset-type",
        choices=["webdataset", "csv", "synthetic", "auto", "icar", "vl_imagenet"],
        default="csv",
        help="Dataset type for training data.",
    )
    parser.add_argument(
        "--val-dataset-type",
        choices=["webdataset", "csv", "synthetic", "auto", "icar", "vl_imagenet"],
        default="csv",
        help="Dataset type for validation data.",
    )
    parser.add_argument(
        "--dataset-resampled",
        default=False,
        action="store_true",
        help="Accepted for compatibility. Cache generation always uses deterministic traversal.",
    )
    parser.add_argument(
        "--csv-separator",
        type=str,
        default="\t",
        help="CSV separator.",
    )
    parser.add_argument(
        "--csv-img-key",
        type=str,
        default="filepath",
        help="CSV image column name.",
    )
    parser.add_argument(
        "--csv-caption-key",
        type=str,
        default="title",
        help="CSV caption column name.",
    )
    parser.add_argument(
        "--csv-caption-candidates-keys",
        type=str,
        default="",
        help=(
            "Comma-separated CSV columns that provide additional candidate captions, "
            "such as synthetic captions generated by a captioner or LLM."
        ),
    )
    parser.add_argument(
        "--csv-synthetic-caption-keys",
        type=str,
        default="",
        help=(
            "Comma-separated subset of candidate caption columns that should be tagged as synthetic. "
            "If omitted, all candidate caption columns are treated as synthetic."
        ),
    )
    parser.add_argument(
        "--csv-metadata-keys",
        type=str,
        default="",
        help=(
            "Comma-separated CSV columns to copy into cache metadata. "
            "Useful for precomputed disagreement, caption quality, or domain-specific scores."
        ),
    )
    parser.add_argument(
        "--cache-density-k",
        type=int,
        default=0,
        help=(
            "If > 0, compute a local density score from image features using the mean cosine similarity "
            "to the top-k nearest neighbours. This is most practical for small or medium subsets."
        ),
    )
    parser.add_argument(
        "--cache-density-chunk-size",
        type=int,
        default=2048,
        help="Chunk size used when computing optional density scores.",
    )
    parser.add_argument(
        "--sup-batch-size",
        type=int,
        default=64,
        help="Accepted for compatibility with multitask training configs.",
    )
    parser.add_argument(
        "--vl-batch-size",
        type=int,
        default=64,
        help="Accepted for compatibility with multitask training configs.",
    )
    parser.add_argument(
        "--num-per-class",
        type=int,
        default=1,
        help="Accepted for compatibility with ICAR configs.",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=0,
        help="Random seed placeholder for compatibility.",
    )
    parser.add_argument(
        "--force-quick-gelu",
        default=False,
        action="store_true",
        help="Force QuickGELU on non-OpenAI transformer models.",
    )
    parser.add_argument(
        "--force-custom-text",
        default=False,
        action="store_true",
        help="Force CustomTextCLIP.",
    )
    parser.add_argument(
        "--pretrained-image",
        default=False,
        action="store_true",
        help="Load pretrained image tower weights when supported.",
    )
    parser.add_argument(
        "--torchscript",
        default=False,
        action="store_true",
        help="TorchScript the teacher model.",
    )
    parser.add_argument(
        "--image-mean",
        type=float,
        nargs="+",
        default=None,
        metavar="MEAN",
        help="Override image mean.",
    )
    parser.add_argument(
        "--image-std",
        type=float,
        nargs="+",
        default=None,
        metavar="STD",
        help="Override image std.",
    )
    parser.add_argument(
        "--verbose",
        default=False,
        action="store_true",
        help="Enable verbose logging.",
    )

    parsed_args, unknown = parser.parse_known_args(args)
    if unknown:
        logging.warning("Ignoring unsupported arguments: %s", " ".join(unknown))
    return parsed_args


def setup_logging(verbose: bool):
    level = logging.DEBUG if verbose else logging.INFO
    logging.basicConfig(
        level=level,
        format="%(asctime)s | %(levelname)s | %(message)s",
    )


def resolve_device(device_arg: str):
    import torch

    if device_arg:
        return torch.device(device_arg)
    return torch.device("cuda" if torch.cuda.is_available() else "cpu")


def resolve_input_spec(args) -> Tuple[str, str, str]:
    if args.train_data:
        return args.train_data, args.data_root, args.dataset_type
    if args.val_data:
        return args.val_data, args.val_data_root, args.val_dataset_type
    raise ValueError("One of --train-data or --val-data must be provided.")


def resolve_dataset_type(data_path: str, dataset_type: str) -> str:
    if dataset_type != "auto":
        return dataset_type

    ext = data_path.split(".")[-1]
    if ext in ("csv", "tsv"):
        return "csv"
    if ext == "tar":
        return "webdataset"
    raise ValueError(f"Unsupported auto dataset type for path: {data_path}")


def get_pad_token_id(tokenizer) -> int:
    if hasattr(tokenizer, "tokenizer"):
        pad_id = tokenizer.tokenizer.pad_token_id
        if pad_id is not None:
            return int(pad_id)
    return 0


def get_tokenized_caption_length(text_tokens, pad_token_id: int) -> int:
    return int(text_tokens.ne(pad_token_id).sum().item())


def parse_comma_separated_list(raw_value: str) -> List[str]:
    if not raw_value:
        return []
    values = []
    for item in str(raw_value).split(","):
        item = item.strip()
        if item:
            values.append(item)
    return values


def dedupe_preserve_order(values: Sequence[str]) -> List[str]:
    output = []
    seen = set()
    for value in values:
        if value in seen:
            continue
        output.append(value)
        seen.add(value)
    return output


def normalize_text_value(value) -> str:
    if value is None:
        return ""
    if isinstance(value, str):
        return value.strip()
    try:
        if value != value:
            return ""
    except TypeError:
        pass
    return str(value).strip()


def is_valid_text_value(text: str) -> bool:
    text = normalize_text_value(text)
    return bool(text) and text.lower() not in {"nan", "none", "null"}


def normalize_metadata_value(value):
    if value is None:
        return None
    if hasattr(value, "item"):
        value = value.item()
    try:
        if value != value:
            return None
    except TypeError:
        pass
    if isinstance(value, str):
        value = value.strip()
        return value if value else None
    return value


def stringify_metadata_value(value) -> str:
    value = normalize_metadata_value(value)
    if value is None:
        return ""
    return str(value)


def get_csv_candidate_caption_keys(args) -> List[str]:
    candidate_keys = dedupe_preserve_order(parse_comma_separated_list(args.csv_caption_candidates_keys))
    return [key for key in candidate_keys if key != args.csv_caption_key]


def get_csv_synthetic_caption_keys(args) -> List[str]:
    synthetic_keys = dedupe_preserve_order(parse_comma_separated_list(args.csv_synthetic_caption_keys))
    candidate_keys = get_csv_candidate_caption_keys(args)
    if not synthetic_keys:
        return list(candidate_keys)
    return [key for key in synthetic_keys if key in candidate_keys]


def get_csv_metadata_keys(args) -> List[str]:
    return dedupe_preserve_order(parse_comma_separated_list(args.csv_metadata_keys))


def compute_caption_quality_score(text: str) -> float:
    text = normalize_text_value(text)
    if not text:
        return 0.0

    lowered = text.lower()
    tokens = [token for token in lowered.split() if token]
    if len(tokens) <= 1:
        tokens = [char for char in lowered if not char.isspace()]
    if not tokens:
        return 0.0

    token_count = len(tokens)
    length_score = min(1.0, token_count / 8.0)
    if token_count > 32:
        length_score *= max(0.0, 1.0 - (token_count - 32) / 32.0)

    frequencies = {}
    for token in tokens:
        frequencies[token] = frequencies.get(token, 0) + 1
    unique_ratio = len(frequencies) / float(token_count)
    repetition_score = 1.0
    if token_count > 1:
        repetition_score = 1.0 - max(0.0, (max(frequencies.values()) - 1) / float(token_count - 1))

    non_space_chars = [char for char in text if not char.isspace()]
    alpha_chars = sum(char.isalpha() for char in non_space_chars)
    digit_chars = sum(char.isdigit() for char in non_space_chars)
    alpha_ratio = alpha_chars / float(max(1, len(non_space_chars)))
    digit_penalty = digit_chars / float(max(1, len(non_space_chars)))

    score = (
        0.35 * length_score +
        0.25 * unique_ratio +
        0.25 * alpha_ratio +
        0.15 * repetition_score -
        0.15 * digit_penalty
    )
    return float(max(0.0, min(1.0, score)))


def compute_similarity_entropy(primary_similarity: float, candidate_similarities: Sequence[float]) -> float | None:
    import torch

    similarities = [float(primary_similarity)] + [float(value) for value in candidate_similarities]
    if len(similarities) <= 1:
        return None
    logits = torch.tensor(similarities, dtype=torch.float32)
    probabilities = torch.softmax(logits, dim=0)
    entropy = -(probabilities * torch.log(probabilities.clamp_min(1e-8))).sum()
    return float(entropy.item())


def compute_similarity_std(values: Sequence[float]) -> float | None:
    if not values:
        return None
    if len(values) == 1:
        return 0.0
    mean_value = sum(values) / float(len(values))
    variance = sum((float(value) - mean_value) ** 2 for value in values) / float(len(values))
    return float(math.sqrt(max(0.0, variance)))


def compute_density_scores(features, k: int, chunk_size: int = 2048) -> List[float]:
    import torch
    import torch.nn.functional as F

    if k <= 0:
        return [0.0] * int(features.shape[0])

    features = F.normalize(features.float(), dim=-1)
    num_samples = int(features.shape[0])
    if num_samples <= 1:
        return [0.0] * num_samples

    effective_k = min(int(k), num_samples - 1)
    density_scores = []
    for start in range(0, num_samples, chunk_size):
        end = min(num_samples, start + chunk_size)
        chunk = features[start:end]
        similarities = chunk @ features.T
        diagonal = torch.arange(end - start)
        similarities[diagonal, start + diagonal] = -float("inf")
        topk = torch.topk(similarities, k=effective_k, dim=1).values
        density_scores.extend(float(value) for value in topk.mean(dim=1).tolist())
    return density_scores


def transpose_collated_columns(columns, batch_size: int) -> List[List]:
    import torch

    if columns is None:
        return [[] for _ in range(batch_size)]
    if isinstance(columns, tuple):
        columns = list(columns)
    if len(columns) == 0:
        return [[] for _ in range(batch_size)]

    rows = [[] for _ in range(batch_size)]
    for column in columns:
        if isinstance(column, torch.Tensor):
            values = column.tolist()
        else:
            values = list(column)
        if len(values) != batch_size:
            raise ValueError(
                f"Expected a collated metadata column of length {batch_size}, but got {len(values)}."
            )
        for index, value in enumerate(values):
            rows[index].append(value.item() if hasattr(value, "item") else value)
    return rows


class MetadataDatasetWrapper:
    def __init__(
        self,
        dataset,
        sample_ids: List[str],
        pad_token_id: int,
        primary_captions: Sequence[str] | None = None,
        candidate_captions: Sequence[Sequence[str]] | None = None,
        extra_metadata_keys: Sequence[str] | None = None,
        extra_metadata_values: Sequence[Sequence] | None = None,
    ):
        self.dataset = dataset
        self.sample_ids = sample_ids
        self.pad_token_id = pad_token_id
        self.primary_captions = list(primary_captions) if primary_captions is not None else None
        self.candidate_captions = [list(values) for values in candidate_captions] if candidate_captions is not None else None
        self.extra_metadata_keys = list(extra_metadata_keys) if extra_metadata_keys is not None else []
        self.extra_metadata_values = [list(values) for values in extra_metadata_values] if extra_metadata_values is not None else None

        if self.primary_captions is not None and len(self.primary_captions) != len(self.dataset):
            raise ValueError("Primary caption metadata length does not match the dataset length.")
        if self.candidate_captions is not None and len(self.candidate_captions) != len(self.dataset):
            raise ValueError("Candidate caption metadata length does not match the dataset length.")
        if self.extra_metadata_values is not None and len(self.extra_metadata_values) != len(self.dataset):
            raise ValueError("Extra metadata length does not match the dataset length.")

    def __len__(self):
        return len(self.dataset)

    def __getitem__(self, index):
        image, text = self.dataset[index]
        caption_length = get_tokenized_caption_length(text, self.pad_token_id)
        primary_caption = ""
        if self.primary_captions is not None:
            primary_caption = self.primary_captions[index]
        candidate_captions = ()
        if self.candidate_captions is not None:
            candidate_captions = tuple(self.candidate_captions[index])
        extra_metadata_values = ()
        if self.extra_metadata_values is not None:
            extra_metadata_values = tuple(self.extra_metadata_values[index])
        return image, text, self.sample_ids[index], caption_length, primary_caption, candidate_captions, extra_metadata_values


def build_csv_like_dataset(
    input_filename: str,
    data_root: str,
    preprocess_fn,
    tokenizer,
    args,
    source_prefix: str,
):
    import pandas as pd
    from training.data import CsvDataset, ImageNetCsvDataset, is_retrieval_dataset_path

    if is_retrieval_dataset_path(input_filename):
        raise ValueError(
            "RetrievalDataset is not supported for cache generation because it does not produce one text per sample."
        )

    dataframe = pd.read_csv(input_filename, sep=args.csv_separator)
    candidate_caption_keys = get_csv_candidate_caption_keys(args)
    extra_metadata_keys = get_csv_metadata_keys(args)
    primary_captions = [normalize_text_value(value) for value in dataframe[args.csv_caption_key].tolist()]
    candidate_captions = []
    for row_index in range(len(dataframe)):
        row_values = []
        for key in candidate_caption_keys:
            if key not in dataframe.columns:
                raise ValueError(f"Candidate caption column '{key}' was not found in {input_filename}.")
            row_values.append(normalize_text_value(dataframe.iloc[row_index][key]))
        candidate_captions.append(row_values)
    extra_metadata_values = []
    for row_index in range(len(dataframe)):
        row_values = []
        for key in extra_metadata_keys:
            if key not in dataframe.columns:
                raise ValueError(f"Metadata column '{key}' was not found in {input_filename}.")
            row_values.append(stringify_metadata_value(dataframe.iloc[row_index][key]))
        extra_metadata_values.append(row_values)

    if "imagenet" in input_filename:
        dataset = ImageNetCsvDataset(
            data_root,
            input_filename,
            preprocess_fn,
            img_key=args.csv_img_key,
            caption_key=args.csv_caption_key,
            sep=args.csv_separator,
            tokenizer=tokenizer,
            deterministic_caption_templates=True,
        )
        primary_captions = [dataset.render_caption(idx) for idx in range(len(dataset))]
        sample_ids = [
            f"{source_prefix}::{idx}::{dataset.class_name[idx]}::{dataset.images[idx]}"
            for idx in range(len(dataset))
        ]
    else:
        dataset = CsvDataset(
            data_root,
            input_filename,
            preprocess_fn,
            img_key=args.csv_img_key,
            caption_key=args.csv_caption_key,
            sep=args.csv_separator,
            tokenizer=tokenizer,
        )
        sample_ids = [
            f"{source_prefix}::{idx}::{dataset.images[idx]}"
            for idx in range(len(dataset))
        ]

    return MetadataDatasetWrapper(
        dataset,
        sample_ids,
        get_pad_token_id(tokenizer),
        primary_captions=primary_captions,
        candidate_captions=candidate_captions if candidate_caption_keys else None,
        extra_metadata_keys=extra_metadata_keys,
        extra_metadata_values=extra_metadata_values if extra_metadata_keys else None,
    )


def build_synthetic_dataset(preprocess_fn, tokenizer, args):
    from training.data import SyntheticDataset

    dataset = SyntheticDataset(
        transform=preprocess_fn,
        image_size=preprocess_fn.transforms[0].size,
        dataset_size=args.train_num_samples or args.val_num_samples or 1,
        tokenizer=tokenizer,
    )
    sample_ids = [f"synthetic::{idx}" for idx in range(len(dataset))]
    return MetadataDatasetWrapper(
        dataset,
        sample_ids,
        get_pad_token_id(tokenizer),
        primary_captions=[dataset.caption for _ in range(len(dataset))],
    )


def build_icar_dataset(preprocess_fn, tokenizer, args, input_filename: str, data_root: str):
    from torch.utils.data import ConcatDataset
    from training.data import CsvDataset, ImageNetCsvDataset

    dataset_names = input_filename.split(",")
    data_root_paths = data_root.split(",") if data_root else []
    if len(dataset_names) != 2 or len(data_root_paths) != 2:
        raise ValueError("ICAR cache generation expects exactly two datasets and two data roots.")

    sup_dataset = ImageNetCsvDataset(
        data_root_paths[0],
        dataset_names[0],
        preprocess_fn,
        img_key=args.csv_img_key,
        caption_key=args.csv_caption_key,
        sep=args.csv_separator,
        tokenizer=tokenizer,
        deterministic_caption_templates=True,
    )
    vl_dataset = CsvDataset(
        data_root_paths[1],
        dataset_names[1],
        preprocess_fn,
        img_key=args.csv_img_key,
        caption_key=args.csv_caption_key,
        sep=args.csv_separator,
        tokenizer=tokenizer,
    )

    wrapped_sup = MetadataDatasetWrapper(
        sup_dataset,
        [
            f"icar_sup::{idx}::{sup_dataset.class_name[idx]}::{sup_dataset.images[idx]}"
            for idx in range(len(sup_dataset))
        ],
        get_pad_token_id(tokenizer),
        primary_captions=[sup_dataset.render_caption(idx) for idx in range(len(sup_dataset))],
    )
    wrapped_vl = MetadataDatasetWrapper(
        vl_dataset,
        [f"icar_vl::{idx}::{vl_dataset.images[idx]}" for idx in range(len(vl_dataset))],
        get_pad_token_id(tokenizer),
        primary_captions=[normalize_text_value(value) for value in vl_dataset.captions],
    )
    return ConcatDataset([wrapped_sup, wrapped_vl])


def build_webdataset_loader(input_shards: str, preprocess_fn, tokenizer, args):
    import webdataset as wds
    from training.data import filter_no_caption_or_no_image, get_dataset_size, log_and_continue

    if args.dataset_resampled:
        logging.warning("--dataset-resampled is ignored for cache generation to keep traversal deterministic.")

    num_samples, _ = get_dataset_size(input_shards)
    if not num_samples:
        num_samples = args.train_num_samples or args.val_num_samples

    pad_token_id = get_pad_token_id(tokenizer)

    def map_sample(sample):
        raw_text = sample["text"]
        if isinstance(raw_text, bytes):
            raw_text = raw_text.decode("utf-8")
        raw_text = normalize_text_value(raw_text)
        text_tokens = tokenizer([raw_text])[0]
        return {
            "image": preprocess_fn(sample["image"]),
            "text": text_tokens,
            "sample_id": f'{sample.get("__url__", "unknown")}::{sample.get("__key__", "unknown")}',
            "caption_length": get_tokenized_caption_length(text_tokens, pad_token_id),
            "primary_caption": raw_text,
            "candidate_captions": tuple(),
            "extra_metadata_values": tuple(),
        }

    dataset = wds.DataPipeline(
        wds.SimpleShardList(input_shards),
        wds.split_by_worker,
        wds.tarfile_to_samples(handler=log_and_continue),
        wds.select(filter_no_caption_or_no_image),
        wds.decode("pilrgb", handler=log_and_continue),
        wds.rename(image="jpg;png", text="txt"),
        wds.map(map_sample),
        wds.to_tuple(
            "image",
            "text",
            "sample_id",
            "caption_length",
            "primary_caption",
            "candidate_captions",
            "extra_metadata_values",
        ),
        wds.batched(args.batch_size, partial=True),
    )

    dataloader = wds.WebLoader(
        dataset,
        batch_size=None,
        shuffle=False,
        num_workers=args.workers,
        persistent_workers=args.workers > 0,
    )
    return dataloader, num_samples


def build_standard_dataloader(dataset, args):
    import torch
    from torch.utils.data import DataLoader

    dataloader = DataLoader(
        dataset,
        batch_size=args.batch_size,
        shuffle=False,
        num_workers=args.workers,
        pin_memory=torch.cuda.is_available(),
        drop_last=False,
        persistent_workers=args.workers > 0,
    )
    return dataloader, len(dataset)


def build_cache_dataloader(args, preprocess_fn, tokenizer):
    from torch.utils.data import ConcatDataset

    input_data, data_root, dataset_type = resolve_input_spec(args)
    dataset_type = resolve_dataset_type(input_data, dataset_type)

    if dataset_type == "webdataset":
        return build_webdataset_loader(input_data, preprocess_fn, tokenizer, args)

    if dataset_type == "synthetic":
        dataset = build_synthetic_dataset(preprocess_fn, tokenizer, args)
        return build_standard_dataloader(dataset, args)

    if dataset_type == "vl_imagenet":
        raise ValueError("vl_imagenet is not supported for cache generation because it contains samples without paired text.")

    if dataset_type == "icar":
        dataset = build_icar_dataset(preprocess_fn, tokenizer, args, input_data, data_root)
        return build_standard_dataloader(dataset, args)

    if dataset_type != "csv":
        raise ValueError(f"Unsupported dataset type for cache generation: {dataset_type}")

    input_files = input_data.split(",")
    data_roots = data_root.split(",") if data_root else [""] * len(input_files)
    if len(data_roots) != len(input_files):
        raise ValueError("The number of dataset roots must match the number of dataset files.")

    datasets = []
    for idx, (input_filename, root) in enumerate(zip(input_files, data_roots)):
        source_prefix = f"csv{idx}:{os.path.basename(input_filename)}"
        datasets.append(
            build_csv_like_dataset(
                input_filename=input_filename,
                data_root=root,
                preprocess_fn=preprocess_fn,
                tokenizer=tokenizer,
                args=args,
                source_prefix=source_prefix,
            )
        )

    dataset = datasets[0] if len(datasets) == 1 else ConcatDataset(datasets)
    return build_standard_dataloader(dataset, args)


def to_caption_length_list(caption_lengths) -> List[int]:
    import torch

    if isinstance(caption_lengths, torch.Tensor):
        return [int(v) for v in caption_lengths.tolist()]
    return [int(v) for v in caption_lengths]


def encode_candidate_caption_batch(
    model,
    tokenizer,
    candidate_caption_rows,
    feature_dim: int,
    device,
    autocast,
):
    import torch
    import torch.nn.functional as F

    batch_size = len(candidate_caption_rows)
    candidate_slots = max((len(row) for row in candidate_caption_rows), default=0)
    if candidate_slots == 0:
        return None, None

    candidate_features = torch.zeros(
        (batch_size, candidate_slots, feature_dim),
        dtype=torch.float16,
    )
    candidate_mask = torch.zeros((batch_size, candidate_slots), dtype=torch.bool)

    flat_captions = []
    flat_positions = []
    for sample_index, row in enumerate(candidate_caption_rows):
        for candidate_index, caption in enumerate(row):
            caption = normalize_text_value(caption)
            if not is_valid_text_value(caption):
                continue
            flat_captions.append(caption)
            flat_positions.append((sample_index, candidate_index))

    if not flat_captions:
        return candidate_features, candidate_mask

    tokenized = tokenizer(flat_captions)
    if isinstance(tokenized, tuple):
        tokenized = tokenized[0]
    tokenized = tokenized.to(device=device, non_blocking=device.type == "cuda")
    with autocast():
        encoded = F.normalize(model.encode_text(tokenized, normalize=True), dim=-1)
    encoded = encoded.cpu().to(torch.float16)

    for encoded_index, (sample_index, candidate_index) in enumerate(flat_positions):
        candidate_features[sample_index, candidate_index] = encoded[encoded_index]
        candidate_mask[sample_index, candidate_index] = True
    return candidate_features, candidate_mask


def maybe_update_density_scores(metadata, image_features, args):
    density_k = int(getattr(args, "cache_density_k", 0))
    if density_k <= 0:
        return metadata

    logging.info("Computing density scores with k=%d for %d samples", density_k, len(metadata))
    density_scores = compute_density_scores(
        image_features,
        k=density_k,
        chunk_size=int(getattr(args, "cache_density_chunk_size", 2048)),
    )
    for entry, density_score in zip(metadata, density_scores):
        entry["density_score"] = float(density_score)
    return metadata


def save_cache(
    args,
    image_features,
    text_features,
    metadata,
    model,
    num_samples: int,
    output_path: str,
    candidate_text_features=None,
    candidate_text_feature_mask=None,
    summary=None,
):
    import torch

    candidate_caption_keys = get_csv_candidate_caption_keys(args)
    synthetic_caption_keys = get_csv_synthetic_caption_keys(args)
    metadata_keys = get_csv_metadata_keys(args)
    cache = {
        "image_features": image_features,
        "text_features": text_features,
        "metadata": metadata,
        "summary": summary or {},
        "config": {
            "teacher_model": args.teacher_model,
            "teacher_pretrained": args.teacher_pretrained,
            "batch_size": args.batch_size,
            "workers": args.workers,
            "device": str(resolve_device(args.device)),
            "precision": args.precision,
            "train_data": args.train_data,
            "val_data": args.val_data,
            "dataset_type": args.dataset_type,
            "val_dataset_type": args.val_dataset_type,
            "data_root": args.data_root,
            "val_data_root": args.val_data_root,
            "feature_dim": int(image_features.shape[1]),
            "num_samples": int(num_samples),
            "logit_scale": float(model.logit_scale.exp().item()),
            "candidate_caption_keys": candidate_caption_keys,
            "synthetic_caption_keys": synthetic_caption_keys,
            "metadata_keys": metadata_keys,
            "cache_density_k": int(getattr(args, "cache_density_k", 0)),
            "cache_format_version": 2,
        },
    }
    if candidate_text_features is not None:
        cache["candidate_text_features"] = candidate_text_features
    if candidate_text_feature_mask is not None:
        cache["candidate_text_feature_mask"] = candidate_text_feature_mask
    output_dir = os.path.dirname(output_path)
    if output_dir:
        os.makedirs(output_dir, exist_ok=True)
    torch.save(cache, output_path)


def main(argv=None):
    import torch
    import torch.nn.functional as F
    import time

    from open_clip import create_model_and_transforms, get_cast_dtype, get_tokenizer
    from training.precision import get_autocast

    args = parse_args(sys.argv[1:] if argv is None else argv)
    setup_logging(args.verbose)
    start_time = time.perf_counter()

    device = resolve_device(args.device)
    logging.info("Building teacher model %s on %s", args.teacher_model, device)

    model, preprocess_train, _ = create_model_and_transforms(
        args.teacher_model,
        pretrained=args.teacher_pretrained,
        precision=args.precision,
        device=device,
        jit=args.torchscript,
        force_quick_gelu=args.force_quick_gelu,
        force_custom_text=args.force_custom_text,
        pretrained_image=args.pretrained_image,
        image_mean=args.image_mean,
        image_std=args.image_std,
    )
    tokenizer = get_tokenizer(args.teacher_model)
    model.eval()

    dataloader, expected_num_samples = build_cache_dataloader(args, preprocess_train, tokenizer)
    logging.info("Starting cache generation with expected samples: %s", expected_num_samples)

    cast_dtype = get_cast_dtype(args.precision)
    use_non_blocking = device.type == "cuda"
    autocast = get_autocast(args.precision) if device.type == "cuda" else nullcontext

    all_image_features = []
    all_text_features = []
    all_candidate_text_features = []
    all_candidate_text_feature_masks = []
    all_metadata = []
    candidate_caption_keys = get_csv_candidate_caption_keys(args)
    synthetic_caption_keys = set(get_csv_synthetic_caption_keys(args))
    extra_metadata_keys = get_csv_metadata_keys(args)

    with torch.no_grad():
        for batch_idx, batch in enumerate(dataloader):
            (
                images,
                texts,
                sample_ids,
                caption_lengths,
                primary_captions,
                candidate_captions_columns,
                extra_metadata_columns,
            ) = batch

            if cast_dtype is not None and device.type != "cpu":
                images = images.to(device=device, dtype=cast_dtype, non_blocking=use_non_blocking)
            else:
                images = images.to(device=device, non_blocking=use_non_blocking)
            texts = texts.to(device=device, non_blocking=use_non_blocking)

            with autocast():
                image_features = F.normalize(model.encode_image(images, normalize=True), dim=-1)
                text_features = F.normalize(model.encode_text(texts, normalize=True), dim=-1)
            similarities = (image_features * text_features).sum(dim=-1)

            image_features_cpu = image_features.cpu().to(torch.float16)
            text_features_cpu = text_features.cpu().to(torch.float16)
            all_image_features.append(image_features_cpu)
            all_text_features.append(text_features_cpu)

            batch_size = len(sample_ids)
            candidate_caption_rows = transpose_collated_columns(candidate_captions_columns, batch_size)
            extra_metadata_rows = transpose_collated_columns(extra_metadata_columns, batch_size)
            candidate_text_features, candidate_text_mask = encode_candidate_caption_batch(
                model=model,
                tokenizer=tokenizer,
                candidate_caption_rows=candidate_caption_rows,
                feature_dim=int(text_features.shape[-1]),
                device=device,
                autocast=autocast,
            )
            if candidate_text_features is not None:
                all_candidate_text_features.append(candidate_text_features)
                all_candidate_text_feature_masks.append(candidate_text_mask)

            caption_length_list = to_caption_length_list(caption_lengths)
            similarity_list = similarities.cpu().tolist()
            primary_captions = [normalize_text_value(value) for value in primary_captions]
            for sample_index, (sample_id, caption_length, similarity) in enumerate(
                zip(sample_ids, caption_length_list, similarity_list)
            ):
                metadata_entry = {
                    "sample_id": str(sample_id),
                    "caption_length": int(caption_length),
                    "image_text_similarity": float(similarity),
                    "difficulty_score": float(1.0 - similarity),
                    "caption_quality": float(compute_caption_quality_score(primary_captions[sample_index])),
                    "candidate_caption_count": int(
                        sum(1 for text in candidate_caption_rows[sample_index] if is_valid_text_value(text))
                    ),
                    "synthetic_caption_count": int(
                        sum(1 for key, text in zip(candidate_caption_keys, candidate_caption_rows[sample_index]) if key in synthetic_caption_keys and is_valid_text_value(text))
                    ),
                }

                candidate_similarity_values = []
                candidate_quality_scores = []
                if candidate_text_features is not None:
                    candidate_feature_row = candidate_text_features[sample_index]
                    candidate_mask_row = candidate_text_mask[sample_index]
                    teacher_image_feature = image_features_cpu[sample_index].float()
                    for candidate_index, key in enumerate(candidate_caption_keys):
                        caption_text = candidate_caption_rows[sample_index][candidate_index] if candidate_index < len(candidate_caption_rows[sample_index]) else ""
                        candidate_quality = float(compute_caption_quality_score(caption_text))
                        candidate_quality_scores.append(candidate_quality)
                        if bool(candidate_mask_row[candidate_index].item()):
                            candidate_similarity = float(
                                (teacher_image_feature * candidate_feature_row[candidate_index].float()).sum().item()
                            )
                            candidate_similarity_values.append(candidate_similarity)
                        else:
                            candidate_similarity = None

                        metadata_entry[f"caption_quality::{key}"] = candidate_quality
                        metadata_entry[f"candidate_text_similarity::{key}"] = candidate_similarity
                        metadata_entry[f"caption_source::{key}"] = "synthetic" if key in synthetic_caption_keys else "candidate"

                if candidate_similarity_values:
                    all_similarity_values = [float(similarity)] + candidate_similarity_values
                    metadata_entry["candidate_text_similarity_mean"] = float(
                        sum(candidate_similarity_values) / float(len(candidate_similarity_values))
                    )
                    metadata_entry["candidate_text_similarity_max"] = float(max(candidate_similarity_values))
                    metadata_entry["teacher_entropy"] = compute_similarity_entropy(similarity, candidate_similarity_values)
                    metadata_entry["caption_disagreement"] = compute_similarity_std(all_similarity_values)
                    metadata_entry["caption_agreement_gap"] = float(max(candidate_similarity_values) - float(similarity))
                    metadata_entry["candidate_caption_quality_mean"] = float(
                        sum(candidate_quality_scores) / float(max(1, len(candidate_quality_scores)))
                    )
                else:
                    metadata_entry["candidate_text_similarity_mean"] = None
                    metadata_entry["candidate_text_similarity_max"] = None
                    metadata_entry["teacher_entropy"] = None
                    metadata_entry["caption_disagreement"] = None
                    metadata_entry["caption_agreement_gap"] = None
                    if candidate_quality_scores:
                        metadata_entry["candidate_caption_quality_mean"] = float(
                            sum(candidate_quality_scores) / float(max(1, len(candidate_quality_scores)))
                        )
                    else:
                        metadata_entry["candidate_caption_quality_mean"] = None

                if sample_index < len(extra_metadata_rows):
                    for key, value in zip(extra_metadata_keys, extra_metadata_rows[sample_index]):
                        metadata_entry[key] = normalize_metadata_value(value)

                all_metadata.append(metadata_entry)

            if batch_idx % 50 == 0:
                logging.info("Processed %d batches", batch_idx + 1)

    if not all_image_features:
        raise RuntimeError("No features were generated. Please check the input dataset arguments.")

    image_features = torch.cat(all_image_features, dim=0)
    text_features = torch.cat(all_text_features, dim=0)
    candidate_text_features = None
    candidate_text_feature_mask = None
    if all_candidate_text_features:
        candidate_text_features = torch.cat(all_candidate_text_features, dim=0)
        candidate_text_feature_mask = torch.cat(all_candidate_text_feature_masks, dim=0)
    all_metadata = maybe_update_density_scores(all_metadata, image_features, args)
    output_path = os.path.abspath(args.output_cache)
    elapsed_seconds = time.perf_counter() - start_time
    summary = {
        "num_samples": int(len(all_metadata)),
        "feature_dim": int(image_features.shape[1]),
        "has_candidate_text_features": candidate_text_features is not None,
        "candidate_caption_slots": int(candidate_text_features.shape[1]) if candidate_text_features is not None else 0,
        "elapsed_seconds": float(elapsed_seconds),
        "elapsed_hours": float(elapsed_seconds / 3600.0),
        "image_feature_bytes": int(image_features.numel() * image_features.element_size()),
        "text_feature_bytes": int(text_features.numel() * text_features.element_size()),
        "candidate_text_feature_bytes": int(candidate_text_features.numel() * candidate_text_features.element_size()) if candidate_text_features is not None else 0,
    }

    save_cache(
        args=args,
        image_features=image_features,
        text_features=text_features,
        metadata=all_metadata,
        model=model,
        num_samples=len(all_metadata),
        output_path=output_path,
        candidate_text_features=candidate_text_features,
        candidate_text_feature_mask=candidate_text_feature_mask,
        summary=summary,
    )

    cache_size_mb = os.path.getsize(output_path) / (1024.0 * 1024.0)
    logging.info(
        "Saved cache with %d samples to %s (%.2f MB, %.2f min)",
        len(all_metadata),
        output_path,
        cache_size_mb,
        elapsed_seconds / 60.0,
    )
    print(output_path)
    return output_path


if __name__ == "__main__":
    main()
